import GeneralNavbar from "@/components/generalNavbar/GeneralNavbar";
import "./globals.css";
import { Inter } from "next/font/google";
import GeneralFooter from "@/components/generalFooter/GeneralFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Subsync News",
  description: "Generated by create next app",
  icons: {
    icon: "./images/logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative min-h-[100dvh] pb-10">
          <GeneralNavbar />
          {children}
          <GeneralFooter />
        </div>
      </body>
    </html>
  );
}
