import Providers from "@/lib/react_query/provider";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Subsync News",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="b bg-gray- min-h-screen">
          <AuthProvider>
            <Providers>{children}</Providers>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
